# Generated by Django 3.2.12 on 2022-04-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrightTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_bright', models.TimeField(blank=True, max_length=30)),
                ('bright_count', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BrightTimeRisk',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_bright', models.IntegerField(blank=True)),
                ('bright_count', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CabinetCount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CheckBoxImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_list', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CheckBrightMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='chkboxcourse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coursename', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentImageInTOI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cur', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IpConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=16)),
                ('mask', models.CharField(max_length=16)),
                ('gateway', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='ManualCount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('manual_count', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RowColCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=64)),
                ('col', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='RunButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('decade', models.IntegerField(default=1980)),
                ('blurb', models.TextField()),
                ('url', models.URLField()),
                ('image_url', models.URLField()),
            ],
        ),
    ]
