# Generated by Django 3.2.12 on 2022-04-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipconfig',
            name='gateway',
            field=models.CharField(default='0', max_length=16),
        ),
        migrations.AlterField(
            model_name='ipconfig',
            name='ip',
            field=models.CharField(default='0', max_length=16),
        ),
        migrations.AlterField(
            model_name='ipconfig',
            name='mask',
            field=models.CharField(default='0', max_length=16),
        ),
    ]
