# Generated by Django 3.2.12 on 2022-06-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20220429_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrightSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_bright', models.TimeField(blank=True, max_length=30)),
                ('bright_count', models.IntegerField(blank=True)),
            ],
        ),
    ]
