# Generated by Django 3.2.12 on 2022-06-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_brightschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brightschedule',
            name='bright_count',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='brightschedule',
            name='time_bright',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
