# Generated by Django 3.2.12 on 2022-06-08 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_auto_20220607_1119'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BrightTime',
            new_name='AutoBright',
        ),
        migrations.RenameModel(
            old_name='RunButton',
            new_name='ButtonMonitoring',
        ),
        migrations.RenameModel(
            old_name='Picture',
            new_name='Images',
        ),
        migrations.RenameModel(
            old_name='ManualCount',
            new_name='ManualBright',
        ),
        migrations.RenameModel(
            old_name='RowColCount',
            new_name='RowColCabinet',
        ),
        migrations.RenameModel(
            old_name='BrightSchedule',
            new_name='ScheduleBright',
        ),
        migrations.DeleteModel(
            name='BrightTimeRisk',
        ),
        migrations.DeleteModel(
            name='CheckBoxImage',
        ),
        migrations.DeleteModel(
            name='CheckBrightMode',
        ),
        migrations.DeleteModel(
            name='chkboxcourse',
        ),
    ]
