# Generated by Django 3.2.12 on 2022-06-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_auto_20220608_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpConfigLAN',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(default='0', max_length=16)),
                ('mask', models.CharField(default='0', max_length=16)),
                ('gateway', models.CharField(default='0', max_length=16)),
            ],
        ),
    ]
