# Generated by Django 3.0.2 on 2021-09-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('number_of_broken', models.CharField(max_length=100)),
                ('percent_broken', models.CharField(max_length=100)),
            ],
        ),
    ]
