# Generated by Django 3.0.2 on 2021-09-09 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_modules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modules',
            name='cabinet',
        ),
        migrations.AddField(
            model_name='cabinets',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cabinets', to='api.Modules'),
            preserve_default=False,
        ),
    ]
