# Generated by Django 3.0.2 on 2021-09-14 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210914_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabinets',
            name='module',
        ),
        migrations.AddField(
            model_name='modules',
            name='cabinet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='api.Cabinets'),
            preserve_default=False,
        ),
    ]
