# Generated by Django 3.0.2 on 2021-09-14 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210914_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='cabinet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='api.Cabinets'),
        ),
    ]
