# Generated by Django 3.0.2 on 2021-09-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210914_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinets',
            name='item',
            field=models.CharField(max_length=100, verbose_name='Номер кабинета'),
        ),
    ]
