# Generated by Django 3.0.2 on 2021-09-15 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210915_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modules',
            name='blue_module',
        ),
        migrations.RemoveField(
            model_name='modules',
            name='green_module',
        ),
        migrations.RemoveField(
            model_name='modules',
            name='red_module',
        ),
        migrations.AlterField(
            model_name='modules',
            name='module_broken',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ColorPixel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red_module', models.CharField(max_length=10000)),
                ('green_module', models.CharField(max_length=10000)),
                ('blue_module', models.CharField(max_length=10000)),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='api.Modules')),
            ],
        ),
    ]
