# Generated by Django 3.0.2 on 2021-09-15 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210915_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='cabinet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='api.Cabinets', verbose_name='Номер кабинета'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='item_module',
            field=models.CharField(max_length=100, verbose_name='Номер модуля'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='module_broken',
            field=models.CharField(max_length=100, null=True, verbose_name='Процент битых пикселей'),
        ),
    ]
