# Generated by Django 3.0.2 on 2021-10-15 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210915_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorpixel',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color_pixel', to='api.Modules'),
        ),
    ]
